"""Canonical beginning-to-end journey for every payment family."""

from __future__ import annotations

from copy import deepcopy


def _j(when: str, start: str, process: str, confirm: str, close: str, failure: str, real: str) -> dict[str, str]:
    return {
        "when": when,
        "start": start,
        "process": process,
        "confirm": confirm,
        "close": close,
        "failure": failure,
        "real": real,
    }


JOURNEYS = {
    "cash": _j(
        "Cobro presencial sin red electrónica.",
        "Cajero abre turno y registra monto.",
        "Recibe efectivo y emite recibo único.",
        "Cuenta caja con segundo responsable.",
        "Deposita y concilia recibos contra banco.",
        "Faltante/sobrante queda como excepción; nunca se borra.",
        "Caja web + roles + impresora + PostgreSQL + archivo bancario.",
    ),
    "paper": _j(
        "Cheque u orden física con cobro diferido.",
        "Registra emisor, monto, fecha e imagen restringida.",
        "Entrega el documento al banco y queda PENDING.",
        "El banco informa cobro o devolución.",
        "Aplica asiento final y concilia cartola.",
        "Cheque devuelto revierte disponibilidad y abre cobranza.",
        "Backoffice + custodia + API/archivo bancario + reglas locales.",
    ),
    "cards": _j(
        "Pago inmediato con tarjeta física o digital.",
        "Backend crea order/payment intent.",
        "PSP tokeniza, autentica y autoriza; luego captura.",
        "Webhook o consulta confirma la captura.",
        "Adquirente liquida; comercio concilia fees y disputas.",
        "Timeout queda UNKNOWN; chargeback se registra por separado.",
        "Checkout alojado + REST API + webhook + PostgreSQL + PCI DSS.",
    ),
    "chile-webpay": _j(
        "Tarjetas en Chile mediante checkout alojado.",
        "Backend crea transacción Webpay y guarda token.",
        "Cliente paga en Transbank y vuelve al comercio.",
        "Backend ejecuta commit una sola vez; status recupera timeout.",
        "Reporte Transbank se concilia con ledger y banco.",
        "Retorno sin commit no prueba pago; UNKNOWN se consulta.",
        "Contrato Transbank + REST Webpay + callback + credenciales separadas.",
    ),
    "chile-oneclick": _j(
        "Cobros posteriores a una tarjeta previamente inscrita.",
        "Start/finish inscribe y entrega tbk_user.",
        "Backend autoriza por tienda usando token protegido.",
        "Status confirma; webhook/consulta actualiza la orden.",
        "Conciliar autorizaciones, refunds y liquidación por tienda.",
        "Baja o rechazo no permite reutilizar una inscripción inválida.",
        "Contrato Oneclick + REST + vault cifrado + consentimiento y límites.",
    ),
    "chile-khipu": _j(
        "Transferencia cuenta a cuenta iniciada desde el comercio.",
        "Backend crea pago Khipu con referencia y callbacks.",
        "Cliente autoriza en su experiencia bancaria.",
        "Webhook autenticado o consulta confirma el payment ID.",
        "Abono bancario se concilia contra la misma referencia.",
        "Callback perdido se recupera consultando; nunca por captura de pantalla.",
        "Cuenta cobrador + Payment API + webhook HTTPS + llave en secret manager.",
    ),
    "mercado-pago": _j(
        "Checkout regional con tarjetas y otros medios.",
        "Frontend tokeniza o redirige; backend crea orden.",
        "Payments/Orders API procesa con idempotency key.",
        "Webhook validado y consulta fijan el estado.",
        "Reporte y disponibilidad del dinero se concilian.",
        "Evento duplicado se reconoce sin repetir ledger ni entrega.",
        "Cuenta vendedor + app test + SDK frontend + REST backend + webhooks.",
    ),
    "acceptance-devices": _j(
        "Cobro presencial en POS, mPOS o SoftPOS.",
        "Caja envía monto y referencia al terminal.",
        "Dispositivo certificado lee y autentica la tarjeta.",
        "Terminal/adquirente devuelve autorización y voucher.",
        "Cierre de lote se concilia con caja y banco.",
        "Desconexión exige consulta/reversa; no repetir venta a ciegas.",
        "Terminal certificado + SDK/protocolo de caja + gestión de dispositivos.",
    ),
    "tokenized-wallets": _j(
        "Apple Pay, Google Pay u otra wallet tokenizada.",
        "Usuario elige wallet en dominio/app registrado.",
        "Wallet crea token de red y criptograma.",
        "Backend/PSP valida token y confirma autorización.",
        "Liquidación y disputa siguen el rail de tarjeta.",
        "Token inválido expira; fallback no debe exponer PAN.",
        "SDK wallet + validación de dominio + PSP + gestión de claves.",
    ),
    "stored-value": _j(
        "Gift card o saldo mantenido por el propio programa.",
        "Identifica cuenta y saldo disponible.",
        "Reserva atómica evita gastar dos veces.",
        "Captura consume saldo o libera la reserva.",
        "Ledger demuestra saldo y pasivo del programa.",
        "Carrera o timeout se resuelve por idempotencia y reserva expirable.",
        "API propia + PostgreSQL transaccional + ledger + reglas regulatorias.",
    ),
    "mobile-money": _j(
        "Pago desde saldo móvil con red de agentes.",
        "Identifica wallet, cliente y agente.",
        "Operador valida PIN/OTP y mueve saldo.",
        "Referencia del operador confirma el pago.",
        "Saldos, comisiones y float de agentes se concilian.",
        "Falta de liquidez o reversa abre una excepción trazable.",
        "Contrato operador + API/USSD + KYC + gestión de agentes y float.",
    ),
    "qr": _j(
        "Iniciar un pago escaneando un código.",
        "Genera QR firmado, único y expirable.",
        "App interpreta datos e inicia el rail subyacente.",
        "API/webhook del rail confirma; el QR no confirma.",
        "Conciliar referencia QR contra abono o adquirente.",
        "QR sustituido/expirado se rechaza; duplicado no reaplica.",
        "Estándar QR + firma + backend + proveedor bancario o wallet.",
    ),
    "bank-transfer": _j(
        "Pago directo entre cuentas bancarias.",
        "Entrega beneficiario y referencia irrepetible.",
        "Cliente o API bancaria instruye transferencia.",
        "Cartola/API autoritativa confirma el abono.",
        "Concilia monto, moneda, referencia y fecha valor.",
        "Comprobante visual se ignora; diferencia queda pendiente.",
        "Cuenta empresa + API/open banking o archivos + conciliador.",
    ),
    "ach": _j(
        "Transferencias masivas diferidas por lote.",
        "Crea lote válido, totales de control y fecha.",
        "Operador acepta archivo y procesa entries.",
        "Acuse y settlement reportan cada entry.",
        "Returns posteriores ajustan ledger y conciliación.",
        "Lote rechazado se corrige completo; return no se oculta.",
        "Acuerdo ODFI/operador + formato NACHA/local + SFTP/API + scheduler.",
    ),
    "direct-debit": _j(
        "Cobros recurrentes autorizados desde cuenta.",
        "Captura mandato, versión y consentimiento.",
        "Presenta débito en la fecha notificada.",
        "Banco informa aceptación o return.",
        "Liquida y concilia por mandato/referencia.",
        "Revocación o fondo insuficiente detiene nuevos intentos según regla.",
        "Proveedor DD + vault de mandatos + batch/API + calendario y avisos.",
    ),
    "instant-payments": _j(
        "Transferencia cuenta a cuenta casi inmediata 24/7.",
        "Resuelve alias/cuenta y crea referencia end-to-end.",
        "Rail valida e instruye en tiempo real.",
        "Confirmación con finalidad declarada cierra el pago.",
        "Concilia mensajes, cuentas técnicas y banco.",
        "UNKNOWN exige status; rapidez no autoriza duplicar.",
        "Participante/proveedor + API ISO 20022/local + operación 24/7.",
    ),
    "payment-initiation": _j(
        "Cobrar mediante link o solicitud compartible.",
        "Crea orden firmada, expirable y de un solo uso.",
        "Cliente abre link y elige el rail final.",
        "Backend confirma por API/webhook del rail.",
        "Atribuye liquidación a orden, campaña o factura.",
        "Link reutilizado o phishing se bloquea por firma/dominio.",
        "Frontend de checkout + URL firmada + PSP + antifraude.",
    ),
    "cash-voucher": _j(
        "Orden digital pagada posteriormente en una red física.",
        "Genera barcode/referencia y vencimiento.",
        "Recaudador recibe efectivo y reporta la operación.",
        "Archivo/API de la red confirma una sola vez.",
        "Settlement del recaudador se concilia con voucher.",
        "Voucher vencido/duplicado se rechaza o queda en excepción.",
        "Contrato recaudador + barcode + API/archivo + conciliación diferida.",
    ),
    "credit-alternatives": _j(
        "Compra financiada en cuotas por un tercero.",
        "Solicita evaluación y muestra costo total.",
        "Cliente consiente; financiador aprueba y paga comercio.",
        "API confirma contrato y desembolso.",
        "Comercio concilia neto; financiador administra cuotas.",
        "Rechazo, mora o devolución siguen flujos separados.",
        "Proveedor BNPL + API/SDK + consentimiento + regulación de crédito.",
    ),
    "carrier-billing": _j(
        "Cargo a factura o saldo del operador móvil.",
        "Verifica línea, elegibilidad y límite.",
        "Usuario confirma con OTP/consentimiento.",
        "Operador devuelve transaction ID.",
        "Reporte divide ingreso entre comercio y operador.",
        "Suscripción o cargo discutido se revierte con evidencia.",
        "Contrato carrier/agregador + API + OTP + gestión de suscripciones.",
    ),
    "platform-payments": _j(
        "Marketplace que cobra y paga a terceros.",
        "Onboarding/KYB habilita cada beneficiario.",
        "Cobro crea split inmutable, comisión y reserva.",
        "Webhook confirma entrada y subledger distribuye.",
        "Payout liquida a vendedores y se concilia.",
        "Refund/chargeback reasigna saldos sin perder el bruto original.",
        "PSP marketplace + cuentas conectadas + subledger + motor de payouts.",
    ),
    "b2b": _j(
        "Pago de facturas con aprobaciones empresariales.",
        "Ingiere factura y valida proveedor.",
        "Segregación de funciones aprueba instrucción.",
        "Banco confirma ejecución y remittance.",
        "ERP, banco y factura se concilian.",
        "Duplicado/cambio de cuenta bloquea pago y escala revisión.",
        "ERP + workflow de aprobación + API bancaria/SFTP + sanciones.",
    ),
    "international": _j(
        "Pago entre países con FX y corresponsales.",
        "Cotiza tasa, fees, beneficiario y vigencia.",
        "Screening y red corresponsal procesan instrucción.",
        "Tracking confirma estado y monto recibido.",
        "Fecha valor, FX y fees se concilian.",
        "Sanción, repair o devolución mantiene trazabilidad del original.",
        "Proveedor cross-border + KYC/AML + FX + SWIFT/ISO 20022.",
    ),
    "high-value": _j(
        "Transferencia urgente de alto valor por RTGS.",
        "Operador autorizado crea instrucción.",
        "Segundo aprobador firma; rail gestiona cola/liquidez.",
        "Mensaje de finalidad confirma irrevocabilidad.",
        "Tesorería concilia intradía y posición de liquidez.",
        "Rechazo/cola no se marca pagado; escala a operación crítica.",
        "Acceso institucional + PKI/HSM + doble control + monitoreo RTGS.",
    ),
    "open-finance": _j(
        "Iniciar pago desde una app con consentimiento bancario.",
        "TPP crea consentimiento con alcance y expiración.",
        "Cliente autentica en banco; FAPI entrega token ligado.",
        "Payment ID se consulta hasta estado final.",
        "Banco y comercio concilian referencia end-to-end.",
        "Consentimiento revocado/token vencido exige nueva autorización.",
        "Registro/licencia TPP + OAuth/OIDC FAPI + mTLS + API bancaria.",
    ),
    "digital-assets": _j(
        "Transferir Bitcoin, Lightning u otro activo.",
        "Genera address/invoice y política de expiración.",
        "Wallet firma y red propaga o enruta.",
        "Confirmaciones o payment hash prueban resultado.",
        "Custodia, fees y conversión fiat se concilian.",
        "Reorg, fee insuficiente o pérdida de clave usa runbook específico.",
        "Nodo/custodio + wallet segura + indexador + compliance y recovery.",
    ),
    "machine-payments": _j(
        "Dispositivo paga automáticamente por uso.",
        "Identidad del equipo recibe presupuesto y política.",
        "Medición genera autorización de alcance mínimo.",
        "Servicio confirma consumo y cargo firmado.",
        "Agrega micropagos y concilia por dispositivo.",
        "Equipo comprometido se revoca; límite evita gasto ilimitado.",
        "Identidad de dispositivo + attestation + API + wallet/rail + límites.",
    ),
    "agentic-payments": _j(
        "Un agente de software compra bajo mandato.",
        "Humano define propósito, presupuesto y expiración.",
        "Motor de políticas decide y pide aprobación si corresponde.",
        "Backend ejecuta y guarda evidencia de mandato/resultado.",
        "Ledger y conciliación atribuyen gasto al responsable.",
        "Ambigüedad o exceso de límite detiene, no improvisa.",
        "Agent API + policy engine + aprobación humana + credencial limitada.",
    ),
}


def journey_for(rail_id: str) -> dict[str, str]:
    """Return the canonical journey without exposing mutable shared state."""
    return deepcopy(JOURNEYS[rail_id])
